/**
 * Apple Health Observers
 *
 * @type {Object}
 */
export const Observers = {
  ActiveEnergyBurned: 'ActiveEnergyBurned',
  BasalEnergyBurned: 'BasalEnergyBurned',
  BloodGlucose: 'BloodGlucose',
  BloodPressure: 'BloodPressure',
  BodyFatPercentage: 'BodyFatPercentage',
  BodyMass: 'BodyMass',
  BodyMassIndex: 'BodyMassIndex',
  BodyTemperature: 'BodyTemperature',
  Cycling: 'Cycling',
  DietaryCholesterol: 'DietaryCholesterol',
  HDLCholesterol: 'HDLCholesterol',
  HeartRate: 'HeartRate',
  HeartRateVariabilitySDNN: 'HeartRateVariabilitySDNN',
  Height: 'Height',
  InsulinDelivery: 'InsulinDelivery',
  LDLCholesterol: 'LDLCholesterol',
  MindfulSession: 'MindfulSession',
  OxygenSaturation: 'OxygenSaturation',
  RespiratoryRate: 'RespiratoryRate',
  RestingHeartRate: 'RestingHeartRate',
  Running: 'Running',
  SleepAnalysis: 'SleepAnalysis',
  StairClimbing: 'StairClimbing',
  StepCount: 'StepCount',
  Swimming: 'Swimming',
  TotalCholesterol: 'TotalCholesterol',
  Triglycerides: 'Triglycerides',
  Vo2Max: 'Vo2Max',
  Walking: 'Walking',
  Workout: 'Workout',
  // Clinical types (iOS 12+, requires HKHealthRecords entitlement)
  AllergyRecord: 'AllergyRecord',
  ConditionRecord: 'ConditionRecord',
  CoverageRecord: 'CoverageRecord',
  ImmunizationRecord: 'ImmunizationRecord',
  LabResultRecord: 'LabResultRecord',
  MedicationRecord: 'MedicationRecord',
  ProcedureRecord: 'ProcedureRecord',
  VitalSignRecord: 'VitalSignRecord',
}
